server:
  port: 8070
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmall_study?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  dubbo:
    application: user-service    #dubbo中服务名称
    protocol:
      name: dubbo     #dubbo通信协议名称
    registry:
      address: 192.168.241.130:2181    #zookeeper注册中心的地址
      protocol: zookeeper       #zookeeper的通信协议的名称
    base-package: com.sunshinehubery.gmall   #dubbo服务扫描的路径

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #表示指带有下划线的表字段映射为驼峰命名法
logging:
  level:
    root: info   #日志的级别