server:
  port: 8071
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmall_study?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  dubbo:
    application: manage-service    #dubbo\u4E2D\u670D\u52A1\u540D\u79F0
    protocol:
      name: dubbo     #dubbo\u901A\u4FE1\u534F\u8BAE\u540D\u79F0
    registry:
      address: 192.168.241.130:2181    #zookeeper\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740
      protocol: zookeeper       #zookeeper\u7684\u901A\u4FE1\u534F\u8BAE\u7684\u540D\u79F0
    base-package: com.sunshinehubery.gmall   #dubbo\u670D\u52A1\u626B\u63CF\u7684\u8DEF\u5F84

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #\u8868\u793A\u6307\u5E26\u6709\u4E0B\u5212\u7EBF\u7684\u8868\u5B57\u6BB5\u6620\u5C04\u4E3A\u9A7C\u5CF0\u547D\u540D\u6CD5
logging:
  level:
    root: info   #\u65E5\u5FD7\u7684\u7EA7\u522B